/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SpeakersRouteImport } from './routes/speakers'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as BrandTemplateRouteImport } from './routes/brand-template'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SpeakersIdRouteImport } from './routes/speakers.$id'
import { Route as ProjectsIdRouteImport } from './routes/projects.$id'

const SpeakersRoute = SpeakersRouteImport.update({
  id: '/speakers',
  path: '/speakers',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandTemplateRoute = BrandTemplateRouteImport.update({
  id: '/brand-template',
  path: '/brand-template',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SpeakersIdRoute = SpeakersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => SpeakersRoute,
} as any)
const ProjectsIdRoute = ProjectsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ProjectsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/brand-template': typeof BrandTemplateRoute
  '/library': typeof LibraryRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/speakers': typeof SpeakersRouteWithChildren
  '/projects/$id': typeof ProjectsIdRoute
  '/speakers/$id': typeof SpeakersIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/brand-template': typeof BrandTemplateRoute
  '/library': typeof LibraryRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/speakers': typeof SpeakersRouteWithChildren
  '/projects/$id': typeof ProjectsIdRoute
  '/speakers/$id': typeof SpeakersIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/brand-template': typeof BrandTemplateRoute
  '/library': typeof LibraryRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/speakers': typeof SpeakersRouteWithChildren
  '/projects/$id': typeof ProjectsIdRoute
  '/speakers/$id': typeof SpeakersIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/brand-template'
    | '/library'
    | '/projects'
    | '/speakers'
    | '/projects/$id'
    | '/speakers/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/brand-template'
    | '/library'
    | '/projects'
    | '/speakers'
    | '/projects/$id'
    | '/speakers/$id'
  id:
    | '__root__'
    | '/'
    | '/brand-template'
    | '/library'
    | '/projects'
    | '/speakers'
    | '/projects/$id'
    | '/speakers/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BrandTemplateRoute: typeof BrandTemplateRoute
  LibraryRoute: typeof LibraryRoute
  ProjectsRoute: typeof ProjectsRouteWithChildren
  SpeakersRoute: typeof SpeakersRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/speakers': {
      id: '/speakers'
      path: '/speakers'
      fullPath: '/speakers'
      preLoaderRoute: typeof SpeakersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand-template': {
      id: '/brand-template'
      path: '/brand-template'
      fullPath: '/brand-template'
      preLoaderRoute: typeof BrandTemplateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/speakers/$id': {
      id: '/speakers/$id'
      path: '/$id'
      fullPath: '/speakers/$id'
      preLoaderRoute: typeof SpeakersIdRouteImport
      parentRoute: typeof SpeakersRoute
    }
    '/projects/$id': {
      id: '/projects/$id'
      path: '/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof ProjectsIdRouteImport
      parentRoute: typeof ProjectsRoute
    }
  }
}

interface ProjectsRouteChildren {
  ProjectsIdRoute: typeof ProjectsIdRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsIdRoute: ProjectsIdRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

interface SpeakersRouteChildren {
  SpeakersIdRoute: typeof SpeakersIdRoute
}

const SpeakersRouteChildren: SpeakersRouteChildren = {
  SpeakersIdRoute: SpeakersIdRoute,
}

const SpeakersRouteWithChildren = SpeakersRoute._addFileChildren(
  SpeakersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BrandTemplateRoute: BrandTemplateRoute,
  LibraryRoute: LibraryRoute,
  ProjectsRoute: ProjectsRouteWithChildren,
  SpeakersRoute: SpeakersRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
